name: Feature Request
description: Request a new feature for the Files website
labels: [feature_request]
body:
  - type: checkboxes
    attributes:
      label: Before you start...
      options:
        - label: Have you refreshed the page? You might be using an old version of the website.
          required: true
        - label: Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what your idea is. Include things like possible use cases, drawbacks, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative solutions
      description: Describe more ways this problem/idea could be solved/implemented.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (screenshots, mockups) relevant to this feature request.

        Tip: You can attach images by highlighting this area and dragging files into it.
